IF OBJECT_ID('CLIENTES') IS NULL
BEGIN
	CREATE TABLE Clientes
	(
		Chave INT NOT NULL IDENTITY PRIMARY KEY,
		Nome VARCHAR(50) NULL,
		Endereco VARCHAR(250) NULL,
		Cidade VARCHAR(250) NULL,
		Bairro VARCHAR(100) NULL,
		Estado VARCHAR(2) NULL,
		CEP VARCHAR(10) NULL,
		Telefone VARCHAR(14) NULL,
		Email VARCHAR(250) NULL,
		DataNascimento DATETIME NULL,
		TipoPessoa CHAR(1) NOT NULL
	)
END

IF OBJECT_ID('USUARIOS') IS NULL
BEGIN
	CREATE TABLE Usuarios
	(
		Id_Usuario INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Usuario VARCHAR(50) NOT NULL,
		Senha VARCHAR(50) NOT NULL,		
	)
END

INSERT INTO USUARIOS(Usuario, Senha) VALUES ('Admin', 'admin123')

SELECT * FROM Usuarios

DROP TABLE Clientes
DROP TABLE Usuarios